# permissions for end users to view tiflowclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tiflowcluster-viewer-role
rules:
- apiGroups:
  - pingcap.com.pingcap.com
  resources:
  - tiflowclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pingcap.com.pingcap.com
  resources:
  - tiflowclusters/status
  verbs:
  - get
